In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import confusion_matrix, accuracy_score

df = pd.read_csv('SNA.csv')

X = df.iloc[:, [2, 3]].values
y = df.iloc[:, 4].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

X_train_bernoulli = (X_train > 0).astype(int)
X_test_bernoulli = (X_test > 0).astype(int)

bernoulli_classifier = BernoulliNB()
bernoulli_classifier.fit(X_train_bernoulli, y_train)
y_pred_bernoulli = bernoulli_classifier.predict(X_test_bernoulli)
print("Bernoulli Naïve Bayes Accuracy:", accuracy_score(y_test, y_pred_bernoulli))
print("Bernoulli Naïve Bayes Confusion Matrix:\n", confusion_matrix(y_test, y_pred_bernoulli), "\n\n")

Gaussian Naïve Bayes Accuracy: 0.9
Gaussian Naïve Bayes Confusion Matrix:
 [[65  3]
 [ 7 25]] 


Multinomial Naïve Bayes Accuracy: 0.68
Multinomial Naïve Bayes Confusion Matrix:
 [[68  0]
 [32  0]] 


Bernoulli Naïve Bayes Accuracy: 0.79
Bernoulli Naïve Bayes Confusion Matrix:
 [[63  5]
 [16 16]] 


