In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans


n_samples = 300
n_features = 2
n_clusters = 4
random_state = 42

X, y_true = make_blobs(n_samples=n_samples, centers=n_clusters, n_features=n_features, random_state=random_state)


plt.figure(figsize=(8, 6))
plt.scatter(X[:, 0], X[:, 1], s=30, cmap='viridis')
plt.title('Generated Synthetic Data')
plt.xlabel('Feature 1')
plt.ylabel('Feature 2')
plt.grid()
plt.show()


kmeans = KMeans(n_clusters=n_clusters, random_state=random_state)
y_kmeans = kmeans.fit_predict(X)


plt.figure(figsize=(8, 6))
plt.scatter(X[:, 0], X[:, 1], c=y_kmeans, s=30, cmap='viridis', label='Data Points')
plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:, 1], c='red', s=200, marker='X', label='Centroids')
plt.title('K-Means Clustering')
plt.xlabel('Feature 1')
plt.ylabel('Feature 2')
plt.legend()
plt.grid()
plt.show()

Gaussian Naïve Bayes Accuracy: 0.9
Gaussian Naïve Bayes Confusion Matrix:
 [[65  3]
 [ 7 25]] 


Multinomial Naïve Bayes Accuracy: 0.68
Multinomial Naïve Bayes Confusion Matrix:
 [[68  0]
 [32  0]] 


Bernoulli Naïve Bayes Accuracy: 0.79
Bernoulli Naïve Bayes Confusion Matrix:
 [[63  5]
 [16 16]] 


